version: "3.5"
services:
    mysql:
        image: mysql:latest
        expose:
            - 3307
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            # MYSQL_DATABASE: ExpenseManagement
            # MYSQL_USER: root
            # MYSQL_PASSWORD: 1234
            bind-address: 0.0.0.0
        volumes:
            - db-volume:/var/lib/mysql
            - ./src/ExpenseManagement/_MySQL_Init_Script:/docker-entrypoint-initdb.d
        networks:
            - backend

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - backend
        depends_on:
            - mysql

    app:
        build:
            context: ./src/ExpenseManagement
            dockerfile: Dockerfile
        ports:
            - 5000:80
            # - 5001:443
        environment:
            DBHOST: "mysql"
            DBPORT: 3306
            DBNAME: "ExpenseManagement"
            DBUSER: "root"
            DBPASSWORD: 1234
            ASPNETCORE_ENVIRONMENT: "Development"
        networks:
            - frontend
            - backend
        depends_on:
            - mysql

volumes:
    db-volume:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
