version: '3.5'
services:
    # mvc:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     networks:
    #         - frontend
    #         - backend
    #     ports:
    #         - 3000:80
    #     environment:
    #         - DBHOST=mysql
    mysql:
        image: mysql:latest
        expose:
            - 3307
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            # MYSQL_DATABASE: mydb
            # MYSQL_USER: userapp
            # MYSQL_PASSWORD: 1234
            bind-address: 0.0.0.0
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - backend

volumes:
    db-volume:

networks: 
    backend:
        driver: bridge
